config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
  end
 
 root to: 'questions#index'
 get '/login', to: 'sessions#new'
 post '/login', to: 'sessions#create'
 
 resources :users

 resources :questions do
  collection do
    get 'search'
  end
  resources :answers, only: [:create]
 end

  namespace :admin do
    resources :questions
  end

  namespace :admin do
    resources :users
  end

  delete '/logout', to: 'sessions#destroy'  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_secure_password
  validates :username, presence: true;
  validates :email, presence: true, uniqueness: true
  has_many :questions
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :require_admin

  def index
    solv = params[:resolved] 
    if solv == '1'
      @questions = Question.where(resolved: true)
    elsif solv == '0'
      @questions = Question.where(resolved: false)
    else
      @questions = Question.all
    end
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    redirect_to admin_questions_path, notice: "質問を削除しました。"  
  end

  private 
  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  skip_before_action :login_required
  def new

  end

  def create
    user = User.find_by(email: session_params[:email])  
    if user&.authenticate(session_params[:password]) && user.admin?
      session[:user_id] = user.id
      redirect_to admin_questions_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
  end

  def create
    user = User.new(user_params)
    user.save!
    redirect_to login_path
  end

 def user_params
  params.require(:user).permit(:username, :email, :image, :password, :admin, :password_confirmation)
 end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:question_id]
    @answer.user_id = current_user.id
    @answer.save!
    AnswerMailer.creation_answer_email(@answer).deliver_now
    redirect_to questions_path, notice: "回答しました"
  end

  private
    def answer_params
      params.require(:answer).permit(:content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    solv = params[:resolved] 
    if solv == '1'
      @q = Question.where(resolved: true).ransack(params[:q])
      @questions = @q.result(distinct: true).page(params[:page])
    elsif solv == '0'
      @q = Question.where(resolved: false).ransack(params[:q])
      @questions = @q.result(distinct: true).page(params[:page])
     else
      @q = Question.all.ransack(params[:q])
      @questions = @q.result(distinct: true).page(params[:page])
    end
  end

  def new
    @question = Question.new
  end
  
  def create
    @question = current_user.questions.new(question_params)

    if params[:back].present?
      render :new
      return
    end

    @question.save!
    QuestionMailer.creation_email(@question).deliver_now
    redirect_to questions_path, notice: "質問「#{@question.title}」を投稿しました。"
  end
  
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = Answer.where(question_id: params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update!(question_params)
    redirect_to questions_path
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    redirect_to questions_path, notice: "質問を削除しました。"  
  end
  
  private 


  def question_params
    params.require(:question).permit(:title, :content, :resolved)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])  
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to questions_path, notice: 'ログインしました。'
    else
      render :new
    end
  end
  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

private
  def session_params
    params.require(:session).permit(:email, :password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
  end

  def create
    user = User.new(user_params)
    user.save!
    redirect_to login_path
  end

 def user_params
  params.require(:user).permit(:username, :email, :image, :password, :admin, :password_confirmation)
 end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/user_sessions_helper.rb
module Admin::UserSessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/admin/questions/index.html.slim
h1 質問一覧管理画面


= link_to '新規投稿', new_question_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th 質問タイトル
      th 質問内容
      th
  tbody
    - @questions.each do |question|
      tr
        td= link_to question.title, question_path(question)
        td= question.content
        td= link_to '削除', admin_question_path(question), method: :delete ,data: { confirm: "質問を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/questions/edit.html.slim
h1 質問編集画面

.nav.justify-content-end

  = form_with model: @question, local: true do |f|
    .form-group
      = f.label :質問タイトル
      = f.text_field :title, class: 'form-control', id: 'question_title'
    .form-group
      = f.label :質問内容
      = f.text_area :content, class: 'form-control', id: 'question_content'
    .form-group
      = f.label :解決済みか？
      <br>
      = f.select :resolved, [ ["解決済み","true"],["未解決","false"]]
    = f.submit nil, class: 'btn btn-primary', value: '編集する'

app/views/questions/index.html.slim
h1 質問一覧画面

= search_form_for @q, url: questions_path, class: 'mb-5' do |f|
  .form-group.row 
    = f.label :title_cont, '質問タイトル', class: 'col-sm-2 col-form-label'
  .col-sm-10
    = f.search_field :title_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary', value: '検索'

= link_to '全て', questions_path, class: 'btn btn-primary'
= link_to '未解決', questions_path(@question, :resolved =>0), class: 'btn btn-primary'
= link_to '解決済み', questions_path(@question, :resolved =>1), class: 'btn btn-primary'
<br>
<br>
= link_to '新規投稿', new_question_path, class: 'btn btn-primary'
.mb-3
  = paginate @questions
  = page_entries_info @questions
.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th 投稿者
      th 質問タイトル
      th 質問内容
  tbody
    - @questions.each do |question|
      tr
        td= image_tag question.user.image, size: "40x40" 
        td= link_to question.title, question_path(question)
        td= question.content

app/views/questions/new.html.slim
h1 質問投稿
.nav.justfy-content-end

  = form_with model: @question, url: questions_path, local: true do |f|
    .form_group
      = f.text_field :title, class: 'form-control', id: 'question_title', placeholder: '質問タイトル'
    .form-group 
      = f.text_area :content, rows: 5, class: 'form-control', id: 'question_content', placeholder: '質問内容'
    = f.submit nil, class: 'btn btn-primary' , value: '投稿する'

app/views/questions/show.html.slim
h1 質問詳細画面

.nav.justify-content-end
  = link_to '一覧', questions_path, class: 'nav-link'
  - if @question.user_id == current_user.id
    = link_to '編集', edit_question_path, class: 'btn btn-primary'
    = link_to '削除', question_path, method: :delete ,data: { confirm: "質問を削除します。よろしいですか？"}, class: 'btn btn-danger'
  - else
  table.table.table-hover
    tbody
      tr
        th ID
        td= @question.id
      tr
        th タイトル
        td= @question.title
      tr
        th 質問内容
        td= @question.content
      tr
        th 登録日時
        td= @question.created_at
      tr
        th 更新日時
        td= @question.updated_at

= form_with model: [@question, @answer], local: true do |f|
    .form_group
      = f.text_field :content, class: 'form-control', id: 'answer', placeholder: '回答内容'
    = f.submit nil, class: 'btn btn-primary' , value: '回答する'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th この質問に対する回答
  tbody
    - @answers.each do |answer|
      tr
        td= answer.content

app/views/users/index.html.slim
h1 ユーザー一覧画面

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th アバター画像
      th ユーザー名
  tbody
    - @users.each do |user|
      tr
        td= image_tag user.image, size: "40x40" if user.image.attached?
        td= user.username 
        

app/views/users/new.html.slim
h1 新規登録画面

= form_with model: @user, local: true do |f|
  .form-group
  = f.text_field :username, class: 'form-control', id: 'user_name', placeholder: 'ユーザーネーム'
  br
  .form-group
    = f.text_field :email, class: 'form-control', id: 'user_email', placeholder: 'メールアドレス'
  br
  .form-group
    = f.file_field :image, class: 'form-control'
  .form-check
    = f.check_box :admin, class: 'form-check-input'
    | 管理者権限
  .form-group
    = f.text_field :password, class: 'form-control', id: 'user_password', placeholder: 'パスワード'
  br
  .form-group
    = f.text_field :password_confirmation, class: 'form-control', id: 'user_password_confirm', placeholder: 'パスワード確認'
  br
  = f.submit nil, class: 'btn btn-primary', value: '登録する'

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim